name       : powerdevil
version    : 5.20.2
release    : 58
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.2/powerdevil-5.20.2.tar.xz : 8fa42d77e21dc29eb5e729102717177b78e8eea0962bc7b856ba56dcce808399
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Manages the power settings of KDE Plasma
description: |
    Manages the power settings of KDE Plasma.
builddeps  :
    - pkgconfig(kscreen2)
    - pkgconfig(libKActivities)
    - pkgconfig(libnm)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(upower-glib)
    - pkgconfig(xcb-util)
    - bluez-qt-devel
    - extra-cmake-modules
    - kauth-devel
    - kconfig-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kidletime-devel
    - kio-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kwayland-devel
    - kwindowsystem-devel
    - networkmanager-qt-devel
    - plasma-workspace-devel
    - solid-devel
rundeps    :
    - upower
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/HTML
