name       : powerdevil
version    : 5.14.1
release    : 26
source     :
    - https://cdn.download.kde.org/stable/plasma/5.14.1/powerdevil-5.14.1.tar.xz : acd9926af9820fa5e8bd797a75e4701c1ea7f8ae9c623eee89e005b322e91b3a
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Manages the power settings of KDE Plasma
description: |
    Manages the power settings of KDE Plasma.
builddeps  :
    - pkgconfig(kscreen2)
    - pkgconfig(libKActivities)
    - pkgconfig(NetworkManager)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(upower-glib)
    - pkgconfig(xcb-util)
    - bluez-qt-devel
    - extra-cmake-modules
    - kauth-devel
    - kconfig-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kidletime-devel
    - kio-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kwayland-devel
    - networkmanager-qt-devel
    - plasma-workspace-devel
    - solid-devel
rundeps    :
    - upower
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
