name       : powerdevil
version    : 5.16.1
release    : 36
source     :
    - https://download.kde.org/stable/plasma/5.16.1/powerdevil-5.16.1.tar.xz : 474fdf8f41221169baa7d7eebd7bf4f0c56123807e5dfaf7d9180a74281e1108
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Manages the power settings of KDE Plasma
description: |
    Manages the power settings of KDE Plasma.
builddeps  :
    - pkgconfig(kscreen2)
    - pkgconfig(libKActivities)
    - pkgconfig(NetworkManager)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(upower-glib)
    - pkgconfig(xcb-util)
    - bluez-qt-devel
    - extra-cmake-modules
    - kauth-devel
    - kconfig-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kidletime-devel
    - kio-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kwayland-devel
    - networkmanager-qt-devel
    - plasma-workspace-devel
    - solid-devel
rundeps    :
    - upower
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
