name       : powerdevil
version    : 5.10.3
release    : 3
source     :
    - https://download.kde.org/stable/plasma/5.10.3/powerdevil-5.10.3.tar.xz : 27ae7f82c1436d4248cbfefb3936602ab1abd1ec10508a567d7e4fddac425376
license    : GPL-2.0
component  : desktop.kde.core
summary    : Manages the power settings of KDE Plasma
description: |
    Manages the power settings of KDE Plasma.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(kscreen2)
    - pkgconfig(libKActivities)
    - pkgconfig(NetworkManager)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-util)
    - bluez-qt-devel
    - extra-cmake-modules
    - kauth-devel
    - kconfig-devel
    - kdbusaddons-devel
    - kdelibs4support-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kidletime-devel
    - kio-devel
    - knotifyconfig-devel
    - kwayland-devel
    - networkmanager-qt-devel
    - plasma-workspace-devel
    - solid-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
