name       : powerdevil
version    : 5.23.0
release    : 73
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.0/powerdevil-5.23.0.tar.xz : 06bb0a69faeb9991dec4a752b1f3b1798ff9bb0aa6a201d0c6615e176153504b
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Manages the power settings of KDE Plasma
description: |
    Manages the power settings of KDE Plasma.
optimize   : lto
builddeps  :
    - pkgconfig(libcap)
    - pkgconfig(libnm)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(upower-glib)
    - pkgconfig(xcb-util)
    - bluez-qt-devel
    - kactivities-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kidletime-devel
    - kio-devel
    - knotifyconfig-devel
    - kwayland-devel
    - libkscreen-devel
    - networkmanager-qt-devel
    - plasma-workspace-devel
rundeps    :
    - upower
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
