name       : powerdevil
version    : 5.12.2
release    : 13
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.2/powerdevil-5.12.2.tar.xz : bcdf7662bb9c45fc213744cea323cdd9676bc4a485d660a958046505aa1c352d
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Manages the power settings of KDE Plasma
description: |
    Manages the power settings of KDE Plasma.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(kscreen2)
    - pkgconfig(libKActivities)
    - pkgconfig(NetworkManager)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(upower-glib)
    - pkgconfig(xcb-util)
    - bluez-qt-devel
    - extra-cmake-modules
    - kauth-devel
    - kconfig-devel
    - kdbusaddons-devel
    - kdelibs4support-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kidletime-devel
    - kio-devel
    - knotifyconfig-devel
    - kwayland-devel
    - networkmanager-qt-devel
    - plasma-workspace-devel
    - solid-devel
rundeps    :
    - upower
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
