name       : powerdevil
version    : 5.18.4.1
release    : 50
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.4/powerdevil-5.18.4.1.tar.xz : ccda33366be7bac6e8a0d551d9501a7c394ddda281c806720582630c075fd1ca
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Manages the power settings of KDE Plasma
description: |
    Manages the power settings of KDE Plasma.
builddeps  :
    - pkgconfig(kscreen2)
    - pkgconfig(libKActivities)
    - pkgconfig(libnm)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(upower-glib)
    - pkgconfig(xcb-util)
    - bluez-qt-devel
    - extra-cmake-modules
    - kauth-devel
    - kconfig-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kidletime-devel
    - kio-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kwayland-devel
    - kwindowsystem-devel
    - networkmanager-qt-devel
    - plasma-workspace-devel
    - solid-devel
rundeps    :
    - upower
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
