name       : powerdevil
version    : 5.27.5
release    : 91
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.5/powerdevil-5.27.5.tar.xz : 0379862c57efef4ce980f6c9583d66deafde1ed522f0e129aa50cef038fb500e
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Manages the power settings of KDE Plasma
description: |
    Manages the power settings of KDE Plasma.
optimize   : lto
builddeps  :
    - pkgconfig(ddcutil)
    - pkgconfig(libcap)
    - pkgconfig(libnm)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(upower-glib)
    - pkgconfig(xcb-util)
    - bluez-qt-devel
    - kactivities-devel
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kidletime-devel
    - kio-devel
    - kirigami2-devel
    - knotifyconfig-devel
    - kwayland-devel
    - libkscreen-devel
    - networkmanager-qt-devel
    - plasma-workspace-devel
rundeps    :
    - upower
setup      : |
    %cmake_ninja -DHAVE_DDCUTIL=On
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
