name       : powerdevil
version    : 5.19.5
release    : 56
source     :
    - https://cdn.download.kde.org/stable/plasma/5.19.5/powerdevil-5.19.5.tar.xz : d15f013c50928097f6b719aca46ec2a93a997dcbb7584bcb09f18015cca8ac1a
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Manages the power settings of KDE Plasma
description: |
    Manages the power settings of KDE Plasma.
builddeps  :
    - pkgconfig(kscreen2)
    - pkgconfig(libKActivities)
    - pkgconfig(libnm)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(upower-glib)
    - pkgconfig(xcb-util)
    - bluez-qt-devel
    - extra-cmake-modules
    - kauth-devel
    - kconfig-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kidletime-devel
    - kio-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kwayland-devel
    - kwindowsystem-devel
    - networkmanager-qt-devel
    - plasma-workspace-devel
    - solid-devel
rundeps    :
    - upower
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/HTML
