name       : powerdevil
version    : 5.24.4
release    : 81
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.4/powerdevil-5.24.4.tar.xz : ef70c00e36d4ddbaedeb0efeba68523289e6e112b12951460c8d36075de9546a
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Manages the power settings of KDE Plasma
description: |
    Manages the power settings of KDE Plasma.
optimize   : lto
builddeps  :
    - pkgconfig(libcap)
    - pkgconfig(libnm)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(upower-glib)
    - pkgconfig(xcb-util)
    - bluez-qt-devel
    - kactivities-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kidletime-devel
    - kio-devel
    - kirigami2-devel
    - knotifyconfig-devel
    - kwayland-devel
    - libkscreen-devel
    - networkmanager-qt-devel
    - plasma-workspace-devel
rundeps    :
    - upower
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
