name       : powerdevil
version    : 5.22.2
release    : 70
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.2.1/powerdevil-5.22.2.1.tar.xz : 956fb53ed6f5120a7ab2a07615acbb9144c996689ac792f457b22062f912b796
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Manages the power settings of KDE Plasma
description: |
    Manages the power settings of KDE Plasma.
optimize   : lto
builddeps  :
    - pkgconfig(libcap)
    - pkgconfig(libnm)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(upower-glib)
    - pkgconfig(xcb-util)
    - bluez-qt-devel
    - kactivities-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kidletime-devel
    - kio-devel
    - knotifyconfig-devel
    - kwayland-devel
    - libkscreen-devel
    - networkmanager-qt-devel
    - plasma-workspace-devel
rundeps    :
    - upower
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
